services:
    glances:
        container_name: glances
        image: 'nicolargo/glances:latest-full'
        pid: host
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        restart: unless-stopped
        environment:
            - GLANCES_OPT=-w --enable-plugin containers
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.glances.rule=PathPrefix(`/`)"
            - "traefik.http.routers.glances.entrypoints=glances"
            - "traefik.http.services.glances.loadbalancer.server.port=61208"